//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organisation.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] JobDescription { get; set; }
        public byte[] Number { get; set; }
        public string Department { get; set; }
        public string HourlyPay { get; set; }
        public byte[] Bonus { get; set; }
        public int TypeId { get; set; }
        public Nullable<decimal> HouseRentAllowance { get; set; }
        public Nullable<decimal> MedicalAllowance { get; set; }
    
        public virtual EmployeeType EmployeeType { get; set; }
    }
}
